title: Digital Garden
description: Christians Digital Garden
theme: just-the-docs
color_scheme: catppuccin

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/TheInfinityCyber/digital-garden#

aux_links_new_tab: true